*STEP 0 ;
/****************************************************************************************************************************/
/*1. Program Name:Vivek235_HW10_Program.sas																						*/
/* Program Location: C:\Users\vigupta\OneDrive\Learning\DataScience\Statistics Texas A&M University\657\Homework\Assignment10\Vivek235_HW10_Program.sas		*/
/* Date Created: 4/2/17																									*/							
/* Author: Vivek Kumar Gupta																								*/
/* Purpose:This exercise reinforces concepts covered in the first 16 lectures and brings together a large number
of macro techniques into one assignment.				*/
/****************************************************************************************************************************/

*STEP 0 - Setup of libraries and filerefs.  Use a filename statement to define the path to the PDF output file.;
*1.Create the necessary library references for data sources and destination and file references for output.;

/*STEP 5. If you do not already have A&M in the path to your output files, create a new folder named
A&M. 
Set up the fileref for your ODS PDF destination to point to a file in the A&M path.
Replace the 10 with a user defined macro variable reference and use the appropriate statement
at the beginning of your program to initialize the macro variable with the assignment number.
Use one of the macro functions described in chapter 2 to enclose part of the file path so that
you do not get the message WARNING: Apparent symbolic reference M not resolved in
the log.
*/
%let no=10;
%let filepath=%nrstr(C:\Users\vigupta\OneDrive\Learning\DataScience\Statistics Texas A&M University\657\Homework\Assignment10\A&M\Vivek235_HW)&no._Output.pdf ;
libname orion 'C:\Users\vigupta\OneDrive\Learning\DataScience\Statistics Texas A&M University\657\SQL Files' access=readonly;
filename mymacro 'C:\Users\vigupta\OneDrive\Learning\DataScience\Statistics Texas A&M University\657\Homework\Assignment10\macros';
filename pdfdev "&filepath";
ods escapechar='^';

*STEP 3. At the beginning of your program, set a system option that writes macro variable values to the
SAS log as they are resolved and an option writes to the SAS log the text that is generated by
macro execution.;

/*STEP 4. Use the appropriate option to set up your SAS session so it can find the autocall macro program
saved in step 1.*/
option symbolgen mprint mcompilenote=all mautosource sasautos=(mymacro,sasautos);

/*Open destination device, set no bookmarks to be generated per the output*/
ods pdf file=pdfdev bookmarkgen=no ;

/*STEP 6. Paste the line below into your program*/
%colormac(help); 


/*STEP 7. Call your donate macro that was saved in the autocall library and use arguments that will
produce the output dataset in the work library and select female donors hired between January
1, 1996 and December 31, 2005 (10 years time span).*/

%donate(work, female, 01Jan1996, 31Dec2005);


/*STEP8. Use the catalog procedure to list macros that are stored in the WORK library. 
These macros are created in the work library by the execution of colormac macro up above.  */

title "Compiled Macros in the Work Library";

proc catalog cat=work.sasmacr; 
contents;
quit;

/*STEP 9. Use a data step to create a new table called salary_f9605 based on the Female1996 dataset
created in step 7 and as instructed in assignment*/

data work.salary_f9605;
set work.female1996 (keep= employee_id employee_name salary);
if _N_=1 then do;
call symputx('empId',employee_id);
call symputx('salary',salary);
call symputx(cats('NAME',employee_id),catx(' ',scan(employee_name,-1),scan(employee_name,1)));
end;
call symputx(cats('NAME',employee_id),catx(' ',scan(employee_name,-1),scan(employee_name,1)));
if input(symget('salary'),10.) < salary then do;
call symputx('empId',employee_id);
call symputx('salary',salary);
end;
run;

/*STEP 10.Use the print procedure to print the data portion of the salary_f9605 dataset.Use the macro
variables created above to automatically populate the title. Use an indirect macro reference to
display the name of the highest paid employee and a macro reference to display the highest
salary in the second line of the title. */

title "Salary Analysis of Selected Employees ^n
		Top Salary = %sysfunc(putn(&salary,dollar8.)) to: &&NAME&empid";


proc print data=work.salary_f9605 label noobs;
var employee_id 
	employee_name 
salary;
run;

/*House keeping. Resetting defaults*/
title;
footnote;
option number date nosymbolgen nomprint mcompilenote=none; 
run;

/**Close the device*/
ods pdf close; 

